<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'team_access',],
            ['id' => 18, 'title' => 'team_create',],
            ['id' => 19, 'title' => 'team_edit',],
            ['id' => 20, 'title' => 'team_view',],
            ['id' => 21, 'title' => 'team_delete',],
            ['id' => 22, 'title' => 'internal_notification_access',],
            ['id' => 23, 'title' => 'internal_notification_create',],
            ['id' => 24, 'title' => 'internal_notification_edit',],
            ['id' => 25, 'title' => 'internal_notification_view',],
            ['id' => 26, 'title' => 'internal_notification_delete',],
            ['id' => 27, 'title' => 'course_management_access',],
            ['id' => 28, 'title' => 'trail_management_access',],
            ['id' => 29, 'title' => 'setting_access',],
            ['id' => 30, 'title' => 'coursecategory_access',],
            ['id' => 31, 'title' => 'coursecategory_create',],
            ['id' => 32, 'title' => 'coursecategory_edit',],
            ['id' => 33, 'title' => 'coursecategory_view',],
            ['id' => 34, 'title' => 'coursecategory_delete',],
            ['id' => 35, 'title' => 'trailcategory_access',],
            ['id' => 36, 'title' => 'trailcategory_create',],
            ['id' => 37, 'title' => 'trailcategory_edit',],
            ['id' => 38, 'title' => 'trailcategory_view',],
            ['id' => 39, 'title' => 'trailcategory_delete',],
            ['id' => 40, 'title' => 'coursetag_access',],
            ['id' => 41, 'title' => 'coursetag_create',],
            ['id' => 42, 'title' => 'coursetag_edit',],
            ['id' => 43, 'title' => 'coursetag_view',],
            ['id' => 44, 'title' => 'coursetag_delete',],
            ['id' => 45, 'title' => 'trailtag_access',],
            ['id' => 46, 'title' => 'trailtag_create',],
            ['id' => 47, 'title' => 'trailtag_edit',],
            ['id' => 48, 'title' => 'trailtag_view',],
            ['id' => 49, 'title' => 'trailtag_delete',],
            ['id' => 50, 'title' => 'lesson_access',],
            ['id' => 51, 'title' => 'lesson_create',],
            ['id' => 52, 'title' => 'lesson_edit',],
            ['id' => 53, 'title' => 'lesson_view',],
            ['id' => 54, 'title' => 'lesson_delete',],
            ['id' => 60, 'title' => 'course_access',],
            ['id' => 61, 'title' => 'course_create',],
            ['id' => 62, 'title' => 'course_edit',],
            ['id' => 63, 'title' => 'course_view',],
            ['id' => 64, 'title' => 'course_delete',],
            ['id' => 65, 'title' => 'trail_access',],
            ['id' => 66, 'title' => 'trail_create',],
            ['id' => 67, 'title' => 'trail_edit',],
            ['id' => 68, 'title' => 'trail_view',],
            ['id' => 69, 'title' => 'trail_delete',],
            ['id' => 70, 'title' => 'general_access',],
            ['id' => 71, 'title' => 'general_create',],
            ['id' => 72, 'title' => 'general_edit',],
            ['id' => 73, 'title' => 'general_view',],
            ['id' => 74, 'title' => 'general_delete',],
            ['id' => 75, 'title' => 'coursescertificate_access',],
            ['id' => 76, 'title' => 'coursescertificate_create',],
            ['id' => 77, 'title' => 'coursescertificate_edit',],
            ['id' => 78, 'title' => 'coursescertificate_view',],
            ['id' => 79, 'title' => 'coursescertificate_delete',],
            ['id' => 85, 'title' => 'trailscertificate_access',],
            ['id' => 86, 'title' => 'trailscertificate_create',],
            ['id' => 87, 'title' => 'trailscertificate_edit',],
            ['id' => 88, 'title' => 'trailscertificate_view',],
            ['id' => 89, 'title' => 'trailscertificate_delete',],
            ['id' => 95, 'title' => 'user_action_access',],
            ['id' => 96, 'title' => 'user_action_create',],
            ['id' => 97, 'title' => 'user_action_edit',],
            ['id' => 98, 'title' => 'user_action_view',],
            ['id' => 99, 'title' => 'user_action_delete',],
            ['id' => 100, 'title' => 'faq_management_access',],
            ['id' => 101, 'title' => 'faq_management_create',],
            ['id' => 102, 'title' => 'faq_management_edit',],
            ['id' => 103, 'title' => 'faq_management_view',],
            ['id' => 104, 'title' => 'faq_management_delete',],
            ['id' => 105, 'title' => 'faq_category_access',],
            ['id' => 106, 'title' => 'faq_category_create',],
            ['id' => 107, 'title' => 'faq_category_edit',],
            ['id' => 108, 'title' => 'faq_category_view',],
            ['id' => 109, 'title' => 'faq_category_delete',],
            ['id' => 110, 'title' => 'faq_question_access',],
            ['id' => 111, 'title' => 'faq_question_create',],
            ['id' => 112, 'title' => 'faq_question_edit',],
            ['id' => 113, 'title' => 'faq_question_view',],
            ['id' => 114, 'title' => 'faq_question_delete',],
            ['id' => 115, 'title' => 'content_management_access',],
            ['id' => 116, 'title' => 'content_management_create',],
            ['id' => 117, 'title' => 'content_management_edit',],
            ['id' => 118, 'title' => 'content_management_view',],
            ['id' => 119, 'title' => 'content_management_delete',],
            ['id' => 120, 'title' => 'content_category_access',],
            ['id' => 121, 'title' => 'content_category_create',],
            ['id' => 122, 'title' => 'content_category_edit',],
            ['id' => 123, 'title' => 'content_category_view',],
            ['id' => 124, 'title' => 'content_category_delete',],
            ['id' => 125, 'title' => 'content_tag_access',],
            ['id' => 126, 'title' => 'content_tag_create',],
            ['id' => 127, 'title' => 'content_tag_edit',],
            ['id' => 128, 'title' => 'content_tag_view',],
            ['id' => 129, 'title' => 'content_tag_delete',],
            ['id' => 130, 'title' => 'content_page_access',],
            ['id' => 131, 'title' => 'content_page_create',],
            ['id' => 132, 'title' => 'content_page_edit',],
            ['id' => 133, 'title' => 'content_page_view',],
            ['id' => 134, 'title' => 'content_page_delete',],
            ['id' => 135, 'title' => 'datatrail_access',],
            ['id' => 136, 'title' => 'datatrail_create',],
            ['id' => 137, 'title' => 'datatrail_edit',],
            ['id' => 138, 'title' => 'datatrail_view',],
            ['id' => 139, 'title' => 'datatrail_delete',],
            ['id' => 140, 'title' => 'datacourse_access',],
            ['id' => 141, 'title' => 'datacourse_create',],
            ['id' => 142, 'title' => 'datacourse_edit',],
            ['id' => 143, 'title' => 'datacourse_view',],
            ['id' => 144, 'title' => 'datacourse_delete',],
            ['id' => 145, 'title' => 'datalesson_access',],
            ['id' => 146, 'title' => 'datalesson_create',],
            ['id' => 147, 'title' => 'datalesson_edit',],
            ['id' => 148, 'title' => 'datalesson_view',],
            ['id' => 149, 'title' => 'datalesson_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
